publish message to pulsar Lico-Tom
paashzj/mqtt-java-pulsar pull request #20
Opened 2022-02-16 13:44 UTC by Lico-Tom

publish message to pulsar Lico-Tom

2022-02-16 13:53 UTC, goflutterjava commented on src/test/java/com/github/shoothzj/mjp/client/Mqttv3ClientTest.java
> +public class Mqttv3ClientTest {
we already merge the v3Client test

2022-02-16 13:57 UTC, goflutterjava commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +            log.debug("publish message : {} ", new String(messageBytes));
in any case, we will not print the message content

2022-02-16 14:38 UTC, goflutterjava requested changes

2022-02-16 14:38 UTC, goflutterjava commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +        MqttSessionKey mqttSessionKey = ChannelUtils.getMqttSession(ctx.channel());
mqttSessionKey may be null

2022-02-16 14:38 UTC, goflutterjava commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +        if (mqttTopicKeys.size() != 0) {
this part should protected by lock

2022-02-16 14:39 UTC, goflutterjava commented
@fu-turer @zxJin-x PTAL, thx

2022-02-16 15:22 UTC, fu-turer commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +        producerMap.put(mqttTopicKey, pulsarClient.newProducer()
close producer in `processDisconnect`

2022-02-16 15:25 UTC, Shoothzj commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +                    producerMap.get(mqttTopicKey).send(messageBytes);
Maybe we should judge the qos first, and introduce a config like Qos1NoWait to control if qos1 sendAsync.

Qos0 should sendAsync. I agree

2022-02-16 23:22 UTC, goflutterjava commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +            mqttSessionKey = new MqttSessionKey();
we should fail and disconnect if mqttSession key be null

2022-02-16 23:22 UTC, goflutterjava commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +            producer.sendAsync(messageBytes);
yes, we should handle the callback to print log to locate problems

2022-02-16 23:23 UTC, goflutterjava commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +            MqttPubAckMessage pubAckMessage = (MqttPubAckMessage) MqttMessageFactory.newMessage(
we should handle the send result, if not success, we will not send the `pubAck` msg

2022-02-16 23:24 UTC, goflutterjava commented on src/test/java/com/github/shoothzj/mjp/client/Mqttv3ClientTest.java
> +import com.github.shoothzj.mjp.integrate.MqsarTestUtil;
we do not need commit this file, commits need squash

2022-02-17 03:28 UTC, Shoothzj commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +import org.apache.pulsar.client.api.*;
avoid use start import

2022-02-17 03:29 UTC, Shoothzj commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +        Preconditions.checkNotNull(mqttSessionKey);
don't assert it be null, if null, we need to close the channel

2022-02-17 03:30 UTC, Shoothzj commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +    void processPublish(ChannelHandlerContext ctx, MqttPublishMessage msg) throws PulsarClientException {
what's the behavior if we throws `PulsarClientException ` here

2022-02-17 03:31 UTC, Shoothzj commented on src/main/java/com/github/shoothzj/mjp/MqsarProcessor.java
> +            log.error("Does not support to QoS2 protocol");
should print the mqtt clientId

2022-02-17 09:02 UTC, closed without merging